apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.fullname" . }}-gatewaybridge
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app.kubernetes.io/instance: "gatewaybridge"
spec:
  type: {{ .Values.gatewaybridge.service.type }}
  ports:
    - port: {{ .Values.gatewaybridge.service.port }}
      targetPort: gatewaybridge
      protocol: UDP
      name: gatewaybridge
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: "gatewaybridge"
